/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mortalkombatbversion;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Мария
 */
public class JFrames extends javax.swing.JFrame {

    Game game = new Game();
    Player player;
    Fighter enemy;
    Items[] items = new Items[3];
    String nameElixirButton = "";

    /**
     * Creates new form JFrame
     */
    public JFrames() {
        initComponents();
        game.ReadFromExcel();
        game.WriteToTable(jTable1);
        items[0] = new Items("Малое зелье лечение", 0);
        items[1] = new Items("Большое зелье лечение", 0);
        items[2] = new Items("Крест возрождения", 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fightFrame = new javax.swing.JFrame();
        fightPanel = new javax.swing.JPanel();
        playerPictureLabel = new javax.swing.JLabel();
        attackButton = new javax.swing.JButton();
        defendButton = new javax.swing.JButton();
        playerHealthProgressBar = new javax.swing.JProgressBar();
        enemyPictureLabel = new javax.swing.JLabel();
        enemyHealthProgressBar = new javax.swing.JProgressBar();
        enemyNameLabel = new javax.swing.JLabel();
        enemyDamageLabel = new javax.swing.JLabel();
        playerDamageLabel = new javax.swing.JLabel();
        playerQuantityDamageLabel = new javax.swing.JLabel();
        enemyQuantityDamageLabel = new javax.swing.JLabel();
        playerLevelLabel = new javax.swing.JLabel();
        fightLabel = new javax.swing.JLabel();
        playerQuantityHeathLabel = new javax.swing.JLabel();
        enemyQuantityHealthLabel = new javax.swing.JLabel();
        experienceLabel = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        quantityExperienceLabel = new javax.swing.JLabel();
        quantityPointsLabel = new javax.swing.JLabel();
        enemyLevelLabel = new javax.swing.JLabel();
        turnInfoLabel = new javax.swing.JLabel();
        commentAboutFightLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        specialCommentAboutFightLabel = new javax.swing.JLabel();
        goodsButton = new javax.swing.JButton();
        infoAboutWinnerDialog = new javax.swing.JDialog();
        infoAboutWinnerPanel = new javax.swing.JPanel();
        winnerNameLabel = new javax.swing.JLabel();
        closeInfoAboutWinnerButton = new javax.swing.JButton();
        winWithRecordDialog = new javax.swing.JDialog();
        winWithRecordPanel = new javax.swing.JPanel();
        winWithRecordLabel = new javax.swing.JLabel();
        nameForRecordTableTextField = new javax.swing.JTextField();
        winWithRecordLabel1 = new javax.swing.JLabel();
        winWithRecordLabel2 = new javax.swing.JLabel();
        finishWinWithRecordGameButton = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        winWithoutRecordDialog = new javax.swing.JDialog();
        winWithoutRecordPanel = new javax.swing.JPanel();
        winWithoutRecordLabel = new javax.swing.JLabel();
        winWithoutRecordLabel1 = new javax.swing.JLabel();
        finishWinWithoutRecordGameButton = new javax.swing.JButton();
        bagDialog = new javax.swing.JDialog();
        bagPanel = new javax.swing.JPanel();
        bagLabel = new javax.swing.JLabel();
        smallHealingElixirRadioButton = new javax.swing.JRadioButton();
        bigHealingElixirRadioButton = new javax.swing.JRadioButton();
        rebirthElixirRadioButton = new javax.swing.JRadioButton();
        useElixirButton = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        elixirRestrictionDialog = new javax.swing.JDialog();
        elixirRestrictionPanel = new javax.swing.JPanel();
        elixirRestrictionLabel1 = new javax.swing.JLabel();
        elixirRestrictionLabel2 = new javax.swing.JLabel();
        closeElixirRestrictionButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        gameNameAndPictureLabel = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        showResultsButton = new javax.swing.JButton();

        fightFrame.setResizable(false);
        fightFrame.setSize(new java.awt.Dimension(1000, 700));

        fightPanel.setBackground(new java.awt.Color(255, 255, 255));
        fightPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        playerPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Kitana.png"))); // NOI18N

        attackButton.setBackground(new java.awt.Color(255, 0, 0));
        attackButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        attackButton.setText("Атаковать");
        attackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButtonActionPerformed(evt);
            }
        });

        defendButton.setBackground(new java.awt.Color(255, 204, 0));
        defendButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        defendButton.setText("Защититься");
        defendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defendButtonActionPerformed(evt);
            }
        });

        playerHealthProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        playerHealthProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        playerHealthProgressBar.setMaximum(80);
        playerHealthProgressBar.setMinimum(-1);

        enemyPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Соня.png"))); // NOI18N

        enemyHealthProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        enemyHealthProgressBar.setForeground(new java.awt.Color(0, 255, 0));
        enemyHealthProgressBar.setMinimum(-1);

        enemyNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        enemyNameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        enemyDamageLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        enemyDamageLabel.setText("Damage");

        playerDamageLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playerDamageLabel.setText("Damage");

        playerQuantityDamageLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerQuantityDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playerQuantityDamageLabel.setForeground(new java.awt.Color(255, 0, 0));
        playerQuantityDamageLabel.setText("16");

        enemyQuantityDamageLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyQuantityDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        enemyQuantityDamageLabel.setForeground(new java.awt.Color(255, 0, 0));
        enemyQuantityDamageLabel.setText("16");

        playerLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        playerLevelLabel.setText("0 уровень");

        fightLabel.setBackground(new java.awt.Color(255, 255, 255));
        fightLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        fightLabel.setForeground(new java.awt.Color(0, 0, 153));
        fightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fightLabel.setText("FIGHT");
        fightLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playerQuantityHeathLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerQuantityHeathLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        playerQuantityHeathLabel.setForeground(new java.awt.Color(102, 102, 102));
        playerQuantityHeathLabel.setText("80/80");

        enemyQuantityHealthLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyQuantityHealthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        enemyQuantityHealthLabel.setForeground(new java.awt.Color(102, 102, 102));
        enemyQuantityHealthLabel.setText("80/80");

        experienceLabel.setBackground(new java.awt.Color(255, 255, 255));
        experienceLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        experienceLabel.setForeground(new java.awt.Color(128, 92, 31));
        experienceLabel.setText("experience");

        pointsLabel.setBackground(new java.awt.Color(255, 255, 255));
        pointsLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(128, 92, 31));
        pointsLabel.setText("points");

        quantityExperienceLabel.setBackground(new java.awt.Color(255, 255, 255));
        quantityExperienceLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        quantityExperienceLabel.setForeground(new java.awt.Color(113, 90, 16));
        quantityExperienceLabel.setText("0/40");

        quantityPointsLabel.setBackground(new java.awt.Color(255, 255, 255));
        quantityPointsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        quantityPointsLabel.setForeground(new java.awt.Color(113, 90, 16));
        quantityPointsLabel.setText("00");

        enemyLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        enemyLevelLabel.setText("1 уровень");

        turnInfoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        turnInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        commentAboutFightLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        commentAboutFightLabel.setForeground(new java.awt.Color(204, 0, 0));
        commentAboutFightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerNameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        playerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerNameLabel.setText("Kitana ");

        specialCommentAboutFightLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        specialCommentAboutFightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        goodsButton.setBackground(new java.awt.Color(174, 183, 106));
        goodsButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        goodsButton.setText("Предметы");
        goodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fightPanelLayout = new javax.swing.GroupLayout(fightPanel);
        fightPanel.setLayout(fightPanelLayout);
        fightPanelLayout.setHorizontalGroup(
            fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addComponent(enemyDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyQuantityDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(pointsLabel))
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(quantityPointsLabel)))
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fightPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addComponent(experienceLabel)
                                        .addGap(59, 59, 59))
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addComponent(quantityExperienceLabel)
                                        .addGap(91, 91, 91)))))
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addComponent(playerDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(playerQuantityDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addComponent(playerHealthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(playerQuantityHeathLabel))
                            .addComponent(defendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerPictureLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addComponent(enemyLevelLabel)
                        .addGap(153, 153, 153)
                        .addComponent(fightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(playerLevelLabel)
                        .addGap(165, 165, 165)))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(fightPanelLayout.createSequentialGroup()
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(goodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(enemyQuantityHealthLabel)
                        .addGap(18, 18, 18)
                        .addComponent(enemyHealthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(enemyPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(specialCommentAboutFightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(commentAboutFightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(turnInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fightPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(enemyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        fightPanelLayout.setVerticalGroup(
            fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fightPanelLayout.createSequentialGroup()
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addComponent(fightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fightPanelLayout.createSequentialGroup()
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemyLevelLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playerLevelLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pointsLabel)
                            .addComponent(enemyQuantityHealthLabel)
                            .addComponent(enemyHealthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experienceLabel)
                            .addComponent(playerHealthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(enemyDamageLabel)
                                .addComponent(enemyQuantityDamageLabel)
                                .addComponent(quantityPointsLabel))
                            .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(playerDamageLabel)
                                .addComponent(playerQuantityDamageLabel))
                            .addComponent(quantityExperienceLabel))
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(turnInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(commentAboutFightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(specialCommentAboutFightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(playerPictureLabel))
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(enemyPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(defendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(goodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(enemyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addComponent(playerQuantityHeathLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout fightFrameLayout = new javax.swing.GroupLayout(fightFrame.getContentPane());
        fightFrame.getContentPane().setLayout(fightFrameLayout);
        fightFrameLayout.setHorizontalGroup(
            fightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightFrameLayout.createSequentialGroup()
                .addComponent(fightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fightFrameLayout.setVerticalGroup(
            fightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        infoAboutWinnerPanel.setBackground(new java.awt.Color(179, 226, 217));

        winnerNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        winnerNameLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        winnerNameLabel.setForeground(new java.awt.Color(204, 0, 0));
        winnerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerNameLabel.setText("jLabel18");
        winnerNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        closeInfoAboutWinnerButton.setBackground(new java.awt.Color(114, 218, 142));
        closeInfoAboutWinnerButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        closeInfoAboutWinnerButton.setText("Дальше");
        closeInfoAboutWinnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInfoAboutWinnerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoAboutWinnerPanelLayout = new javax.swing.GroupLayout(infoAboutWinnerPanel);
        infoAboutWinnerPanel.setLayout(infoAboutWinnerPanelLayout);
        infoAboutWinnerPanelLayout.setHorizontalGroup(
            infoAboutWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoAboutWinnerPanelLayout.createSequentialGroup()
                .addGroup(infoAboutWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoAboutWinnerPanelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(closeInfoAboutWinnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoAboutWinnerPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(winnerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        infoAboutWinnerPanelLayout.setVerticalGroup(
            infoAboutWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoAboutWinnerPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(winnerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(closeInfoAboutWinnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout infoAboutWinnerDialogLayout = new javax.swing.GroupLayout(infoAboutWinnerDialog.getContentPane());
        infoAboutWinnerDialog.getContentPane().setLayout(infoAboutWinnerDialogLayout);
        infoAboutWinnerDialogLayout.setHorizontalGroup(
            infoAboutWinnerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoAboutWinnerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoAboutWinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        infoAboutWinnerDialogLayout.setVerticalGroup(
            infoAboutWinnerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoAboutWinnerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoAboutWinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        winWithRecordPanel.setBackground(new java.awt.Color(255, 204, 255));

        winWithRecordLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        winWithRecordLabel.setForeground(new java.awt.Color(255, 0, 0));
        winWithRecordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winWithRecordLabel.setText("Победа на вашей стороне");

        nameForRecordTableTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nameForRecordTableTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameForRecordTableTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameForRecordTableTextFieldActionPerformed(evt);
            }
        });

        winWithRecordLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        winWithRecordLabel1.setForeground(new java.awt.Color(102, 102, 102));
        winWithRecordLabel1.setText("Введите имя своего персонажа для добавления");

        winWithRecordLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        winWithRecordLabel2.setForeground(new java.awt.Color(102, 102, 102));
        winWithRecordLabel2.setText("результата в таблицу рекордов");

        finishWinWithRecordGameButton.setBackground(new java.awt.Color(153, 153, 255));
        finishWinWithRecordGameButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        finishWinWithRecordGameButton.setForeground(new java.awt.Color(51, 51, 51));
        finishWinWithRecordGameButton.setText("Закончить игру");
        finishWinWithRecordGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishWinWithRecordGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winWithRecordPanelLayout = new javax.swing.GroupLayout(winWithRecordPanel);
        winWithRecordPanel.setLayout(winWithRecordPanelLayout);
        winWithRecordPanelLayout.setHorizontalGroup(
            winWithRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winWithRecordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(finishWinWithRecordGameButton)
                .addGap(14, 14, 14))
            .addGroup(winWithRecordPanelLayout.createSequentialGroup()
                .addGroup(winWithRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winWithRecordPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(winWithRecordLabel2))
                    .addGroup(winWithRecordPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(winWithRecordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winWithRecordPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(winWithRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameForRecordTableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(winWithRecordLabel1))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        winWithRecordPanelLayout.setVerticalGroup(
            winWithRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winWithRecordPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(winWithRecordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(winWithRecordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winWithRecordLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(nameForRecordTableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishWinWithRecordGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout winWithRecordDialogLayout = new javax.swing.GroupLayout(winWithRecordDialog.getContentPane());
        winWithRecordDialog.getContentPane().setLayout(winWithRecordDialogLayout);
        winWithRecordDialogLayout.setHorizontalGroup(
            winWithRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winWithRecordDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winWithRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        winWithRecordDialogLayout.setVerticalGroup(
            winWithRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winWithRecordDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winWithRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Таблица рекордов");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Закрыть");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        winWithoutRecordPanel.setBackground(new java.awt.Color(255, 204, 255));

        winWithoutRecordLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        winWithoutRecordLabel.setForeground(new java.awt.Color(255, 0, 0));
        winWithoutRecordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winWithoutRecordLabel.setText("Победа на вашей стороне");

        winWithoutRecordLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        winWithoutRecordLabel1.setForeground(new java.awt.Color(102, 102, 102));
        winWithoutRecordLabel1.setText("К сожалению, Ваш результат не попал в топ 10");

        finishWinWithoutRecordGameButton.setBackground(new java.awt.Color(153, 153, 255));
        finishWinWithoutRecordGameButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        finishWinWithoutRecordGameButton.setForeground(new java.awt.Color(51, 51, 51));
        finishWinWithoutRecordGameButton.setText("Закончить игру");
        finishWinWithoutRecordGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishWinWithoutRecordGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winWithoutRecordPanelLayout = new javax.swing.GroupLayout(winWithoutRecordPanel);
        winWithoutRecordPanel.setLayout(winWithoutRecordPanelLayout);
        winWithoutRecordPanelLayout.setHorizontalGroup(
            winWithoutRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winWithoutRecordPanelLayout.createSequentialGroup()
                .addGroup(winWithoutRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winWithoutRecordPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(winWithoutRecordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winWithoutRecordPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(winWithoutRecordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winWithoutRecordPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(finishWinWithoutRecordGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        winWithoutRecordPanelLayout.setVerticalGroup(
            winWithoutRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winWithoutRecordPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(winWithoutRecordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(winWithoutRecordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(finishWinWithoutRecordGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout winWithoutRecordDialogLayout = new javax.swing.GroupLayout(winWithoutRecordDialog.getContentPane());
        winWithoutRecordDialog.getContentPane().setLayout(winWithoutRecordDialogLayout);
        winWithoutRecordDialogLayout.setHorizontalGroup(
            winWithoutRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winWithoutRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        winWithoutRecordDialogLayout.setVerticalGroup(
            winWithoutRecordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winWithoutRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bagPanel.setBackground(new java.awt.Color(190, 182, 135));

        bagLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        bagLabel.setForeground(new java.awt.Color(51, 51, 51));
        bagLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bagLabel.setText("Мешок предметов");

        smallHealingElixirRadioButton.setBackground(new java.awt.Color(190, 182, 135));
        buttonGroup1.add(smallHealingElixirRadioButton);
        smallHealingElixirRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        smallHealingElixirRadioButton.setText("Малое зелье лечение, 0 шт");
        smallHealingElixirRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallHealingElixirRadioButtonActionPerformed(evt);
            }
        });

        bigHealingElixirRadioButton.setBackground(new java.awt.Color(190, 182, 135));
        buttonGroup1.add(bigHealingElixirRadioButton);
        bigHealingElixirRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bigHealingElixirRadioButton.setText("Большое зелье лечение, 0 шт");
        bigHealingElixirRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigHealingElixirRadioButtonActionPerformed(evt);
            }
        });

        rebirthElixirRadioButton.setBackground(new java.awt.Color(190, 182, 135));
        buttonGroup1.add(rebirthElixirRadioButton);
        rebirthElixirRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rebirthElixirRadioButton.setText("Крест возрождения, 0 шт");

        useElixirButton.setBackground(new java.awt.Color(239, 237, 14));
        useElixirButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        useElixirButton.setText("Использовать");
        useElixirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useElixirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bagPanelLayout = new javax.swing.GroupLayout(bagPanel);
        bagPanel.setLayout(bagPanelLayout);
        bagPanelLayout.setHorizontalGroup(
            bagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagPanelLayout.createSequentialGroup()
                .addGroup(bagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bagPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(bagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bigHealingElixirRadioButton)
                            .addComponent(rebirthElixirRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallHealingElixirRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bagPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(useElixirButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        bagPanelLayout.setVerticalGroup(
            bagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(smallHealingElixirRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bigHealingElixirRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rebirthElixirRadioButton)
                .addGap(50, 50, 50)
                .addComponent(useElixirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bagDialogLayout = new javax.swing.GroupLayout(bagDialog.getContentPane());
        bagDialog.getContentPane().setLayout(bagDialogLayout);
        bagDialogLayout.setHorizontalGroup(
            bagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bagDialogLayout.setVerticalGroup(
            bagDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        elixirRestrictionPanel.setBackground(new java.awt.Color(243, 120, 120));

        elixirRestrictionLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        elixirRestrictionLabel1.setForeground(new java.awt.Color(51, 51, 51));
        elixirRestrictionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elixirRestrictionLabel1.setText("Вы не можете использовать ");

        elixirRestrictionLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        elixirRestrictionLabel2.setForeground(new java.awt.Color(51, 51, 51));
        elixirRestrictionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elixirRestrictionLabel2.setText("этот предмет");

        closeElixirRestrictionButton.setBackground(new java.awt.Color(204, 204, 204));
        closeElixirRestrictionButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeElixirRestrictionButton.setForeground(new java.awt.Color(51, 51, 51));
        closeElixirRestrictionButton.setText("ОК");
        closeElixirRestrictionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeElixirRestrictionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout elixirRestrictionPanelLayout = new javax.swing.GroupLayout(elixirRestrictionPanel);
        elixirRestrictionPanel.setLayout(elixirRestrictionPanelLayout);
        elixirRestrictionPanelLayout.setHorizontalGroup(
            elixirRestrictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elixirRestrictionPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(elixirRestrictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elixirRestrictionPanelLayout.createSequentialGroup()
                        .addComponent(elixirRestrictionLabel1)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elixirRestrictionPanelLayout.createSequentialGroup()
                        .addComponent(elixirRestrictionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(elixirRestrictionPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(closeElixirRestrictionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        elixirRestrictionPanelLayout.setVerticalGroup(
            elixirRestrictionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elixirRestrictionPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(elixirRestrictionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elixirRestrictionLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(closeElixirRestrictionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout elixirRestrictionDialogLayout = new javax.swing.GroupLayout(elixirRestrictionDialog.getContentPane());
        elixirRestrictionDialog.getContentPane().setLayout(elixirRestrictionDialogLayout);
        elixirRestrictionDialogLayout.setHorizontalGroup(
            elixirRestrictionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elixirRestrictionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        elixirRestrictionDialogLayout.setVerticalGroup(
            elixirRestrictionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elixirRestrictionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));
        menuPanel.setForeground(new java.awt.Color(204, 0, 0));

        gameNameAndPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/mortal_combat.jpg"))); // NOI18N

        startGameButton.setBackground(new java.awt.Color(0, 0, 0));
        startGameButton.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        startGameButton.setForeground(new java.awt.Color(255, 0, 0));
        startGameButton.setText("Начать новую игру");
        startGameButton.setBorder(null);
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        showResultsButton.setBackground(new java.awt.Color(0, 0, 0));
        showResultsButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        showResultsButton.setForeground(new java.awt.Color(255, 0, 0));
        showResultsButton.setText("Посмотреть таблицу \nрезультатов");
        showResultsButton.setBorder(null);
        showResultsButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        showResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameNameAndPictureLabel)
                    .addComponent(showResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(showResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameNameAndPictureLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        fightFrame.setVisible(true);

        player = game.newPlayer(playerHealthProgressBar);

        enemy = game.NewEnemy(enemyPictureLabel, enemyNameLabel, enemyQuantityDamageLabel, enemyQuantityHealthLabel, enemyHealthProgressBar);

        game.textChanger.NewRoundTexts(player, enemy, quantityPointsLabel, quantityExperienceLabel, 
                playerLevelLabel, enemyLevelLabel, playerQuantityHeathLabel, enemyQuantityHealthLabel, 
                playerQuantityDamageLabel, turnInfoLabel, commentAboutFightLabel, game.fight.moveNumber, 
                items, smallHealingElixirRadioButton, bigHealingElixirRadioButton, rebirthElixirRadioButton);

    }//GEN-LAST:event_startGameButtonActionPerformed

    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButtonActionPerformed
        game.fight.Hit(player, enemy, 1, enemyQuantityHealthLabel, playerQuantityHeathLabel, infoAboutWinnerDialog,
                winnerNameLabel, game.action, playerHealthProgressBar, enemyHealthProgressBar, winWithRecordDialog,
                winWithoutRecordDialog, fightFrame, game.getResults(), winWithRecordLabel, winWithoutRecordLabel,
                turnInfoLabel, specialCommentAboutFightLabel, commentAboutFightLabel, items, rebirthElixirRadioButton);

    }//GEN-LAST:event_attackButtonActionPerformed

    private void defendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defendButtonActionPerformed
        game.fight.Hit(player, enemy, 0, enemyQuantityHealthLabel, playerQuantityHeathLabel, infoAboutWinnerDialog,
                winnerNameLabel, game.action, playerHealthProgressBar, enemyHealthProgressBar, winWithRecordDialog,
                winWithoutRecordDialog, fightFrame, game.getResults(), winWithRecordLabel, winWithoutRecordLabel,
                turnInfoLabel, specialCommentAboutFightLabel, commentAboutFightLabel, items, rebirthElixirRadioButton);
    }//GEN-LAST:event_defendButtonActionPerformed

    private void closeInfoAboutWinnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInfoAboutWinnerButtonActionPerformed

        enemy = game.fight.NewRound(player, enemyPictureLabel, playerHealthProgressBar, enemyHealthProgressBar,
                enemyNameLabel, enemyQuantityDamageLabel, enemyQuantityHealthLabel, game.action);

        game.textChanger.NewRoundTexts(player, enemy, quantityPointsLabel, quantityExperienceLabel, playerLevelLabel, enemyLevelLabel, playerQuantityHeathLabel, enemyQuantityHealthLabel, playerQuantityDamageLabel,
                turnInfoLabel, commentAboutFightLabel, game.fight.moveNumber, items, smallHealingElixirRadioButton, bigHealingElixirRadioButton, rebirthElixirRadioButton);

        infoAboutWinnerDialog.dispose();
    }//GEN-LAST:event_closeInfoAboutWinnerButtonActionPerformed

    private void nameForRecordTableTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameForRecordTableTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameForRecordTableTextFieldActionPerformed

    private void finishWinWithRecordGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishWinWithRecordGameButtonActionPerformed
        try {
            game.EndGameTop(player, nameForRecordTableTextField, jTable1);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        winWithRecordDialog.dispose();
        nameForRecordTableTextField.setText("");
    }//GEN-LAST:event_finishWinWithRecordGameButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jDialog3.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void showResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultsButtonActionPerformed
        jDialog3.setVisible(true);
        jDialog3.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_showResultsButtonActionPerformed

    private void finishWinWithoutRecordGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishWinWithoutRecordGameButtonActionPerformed
        winWithoutRecordDialog.dispose();
    }//GEN-LAST:event_finishWinWithoutRecordGameButtonActionPerformed

    private void smallHealingElixirRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallHealingElixirRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallHealingElixirRadioButtonActionPerformed

    private void bigHealingElixirRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigHealingElixirRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigHealingElixirRadioButtonActionPerformed

    private void useElixirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useElixirButtonActionPerformed
        if (smallHealingElixirRadioButton.isSelected()) {
            nameElixirButton = "smallHealingElixir";
        }
        if (bigHealingElixirRadioButton.isSelected()) {
            nameElixirButton = "bigHealingElixir";
        }
        if (rebirthElixirRadioButton.isSelected()) {
            nameElixirButton = "rebirthElixir";
        }
        game.action.UseItem(player, items, nameElixirButton, elixirRestrictionDialog, bagDialog);
        game.action.setHealthProgressBar(player, playerHealthProgressBar);
        playerQuantityHeathLabel.setText(player.getHealth() + "/" + player.getMaxHealth());
        game.textChanger.BagText(items, smallHealingElixirRadioButton, bigHealingElixirRadioButton, rebirthElixirRadioButton);
    }//GEN-LAST:event_useElixirButtonActionPerformed

    private void goodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodsButtonActionPerformed
        bagDialog.setVisible(true);
        bagDialog.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_goodsButtonActionPerformed

    private void closeElixirRestrictionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeElixirRestrictionButtonActionPerformed
        elixirRestrictionDialog.dispose();
    }//GEN-LAST:event_closeElixirRestrictionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackButton;
    private javax.swing.JDialog bagDialog;
    private javax.swing.JLabel bagLabel;
    private javax.swing.JPanel bagPanel;
    private javax.swing.JRadioButton bigHealingElixirRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeElixirRestrictionButton;
    private javax.swing.JButton closeInfoAboutWinnerButton;
    private javax.swing.JLabel commentAboutFightLabel;
    private javax.swing.JButton defendButton;
    private javax.swing.JDialog elixirRestrictionDialog;
    private javax.swing.JLabel elixirRestrictionLabel1;
    private javax.swing.JLabel elixirRestrictionLabel2;
    private javax.swing.JPanel elixirRestrictionPanel;
    private javax.swing.JLabel enemyDamageLabel;
    private javax.swing.JProgressBar enemyHealthProgressBar;
    private javax.swing.JLabel enemyLevelLabel;
    private javax.swing.JLabel enemyNameLabel;
    private javax.swing.JLabel enemyPictureLabel;
    private javax.swing.JLabel enemyQuantityDamageLabel;
    private javax.swing.JLabel enemyQuantityHealthLabel;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JFrame fightFrame;
    private javax.swing.JLabel fightLabel;
    private javax.swing.JPanel fightPanel;
    private javax.swing.JButton finishWinWithRecordGameButton;
    private javax.swing.JButton finishWinWithoutRecordGameButton;
    private javax.swing.JLabel gameNameAndPictureLabel;
    private javax.swing.JButton goodsButton;
    private javax.swing.JDialog infoAboutWinnerDialog;
    private javax.swing.JPanel infoAboutWinnerPanel;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nameForRecordTableTextField;
    private javax.swing.JLabel playerDamageLabel;
    private javax.swing.JProgressBar playerHealthProgressBar;
    private javax.swing.JLabel playerLevelLabel;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel playerPictureLabel;
    private javax.swing.JLabel playerQuantityDamageLabel;
    private javax.swing.JLabel playerQuantityHeathLabel;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JLabel quantityExperienceLabel;
    private javax.swing.JLabel quantityPointsLabel;
    private javax.swing.JRadioButton rebirthElixirRadioButton;
    private javax.swing.JButton showResultsButton;
    private javax.swing.JRadioButton smallHealingElixirRadioButton;
    private javax.swing.JLabel specialCommentAboutFightLabel;
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel turnInfoLabel;
    private javax.swing.JButton useElixirButton;
    private javax.swing.JDialog winWithRecordDialog;
    private javax.swing.JLabel winWithRecordLabel;
    private javax.swing.JLabel winWithRecordLabel1;
    private javax.swing.JLabel winWithRecordLabel2;
    private javax.swing.JPanel winWithRecordPanel;
    private javax.swing.JDialog winWithoutRecordDialog;
    private javax.swing.JLabel winWithoutRecordLabel;
    private javax.swing.JLabel winWithoutRecordLabel1;
    private javax.swing.JPanel winWithoutRecordPanel;
    private javax.swing.JLabel winnerNameLabel;
    // End of variables declaration//GEN-END:variables
}
